### ISSUE TITLE
Multiple dataSource and one tableView. SearchController

### ISSUE THREAD

**Issue by amanbolat** [3lvis/DATASource#71] opened 2016-05-19 01:58 UTC
I have UIViewController with one UITableView and 3 lazy instances of dataSource and one optional  that indicates activeDataSource for my tableView. Each dataSource has own predicate, sortDescriptor. I also added UISegmentedControl with 3 segments for each data source and function that will change activeDataSource and reload data. Every time viewDidLoad() i have function, that fetches data from server and sync it with Core Data and it can take 3-4 seconds. This 3-4 seconds i try randomly tap segmentedControl to change my dataSource and i get error:

```
Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.7/UITableView.m:1502
2016-05-19 09:43:19.702 MyApp[9301:2958707] CoreData: error: Serious application error.  An exception was caught from the delegate of NSFetchedResultsController during a call to -controllerDidChangeContent:.  attempt to insert row 0 into section 0, but there are only 0 rows in section 0 after the update with userInfo (null)
```

Yes, i can disable UserInteraction on segmentedControl, but sometimes user doesn't like wait for sync completion and just filter data, that he/she wants. 
In addition i want implement searchController, that will need 4th dataSource, and it will filter data more faster.

Any idea, how avoid this error?

**Comment by 3lvis** [comment] 2016-05-19 07:27
Hi Amanbolat,

Interesting problem. I believe the error is happening because new animations are starting while other ones are in progress. Combining multiple data sources in one table view has given me a lot of headaches in the past, I think we could figure out some workarounds if we manage to reproduce the error in a sample project, but have you considered using 3 table views each one with a different data source and just switch between them when the segmented control changes his value? Might make things much faster.

**Comment by amanbolat** [comment] 2016-05-19 16:32
I will try your method with multiple table views and also will create sample project to reproduce the error.

**Comment by amanbolat** [comment] 2016-05-22 21:14
@3lvis I found problem. Because i have only one tableView and multiple dataSources, each time i change dataSource for my tableView, previous dataSource doesn't stop call functions of it's NSFetchedResultsControllerDelegate functions: 
`controllerWillChangeContent`
`controllerDidChangeContent`
If i'm right all these methods still use tableView and cause problem. 
So i added new `var isUpdatingTableView = true` and this method, that i call when user changes segment of segmentedControl:

```
func segmentValueChanged(segmentedControl: UISegmentedControl) {
    if segmentedControl.selectedSegmentIndex == 0 {
      dataSourceONE.isUpdatingTableView = true
      dataSourceTWO.isUpdatingTableView = false
      dataSourceTHREE.isUpdatingTableView = false
      self.tableView.dataSource = dataSourceONE
      self.activeFRCSource = dataSourceONE
      
    } else if segmentedControl.selectedSegmentIndex == 1 {
      dataSourceTWO.isUpdatingTableView = true
      dataSourceONE.isUpdatingTableView = false
      dataSourceTHREE.isUpdatingTableView = false
      self.tableView.dataSource = dataSourceTWO
      self.activeFRCSource = dataSourceTWO

    } else if segmentedControl.selectedSegmentIndex == 2 {
      dataSourceTHREE.isUpdatingTableView = true
      dataSourceTWO.isUpdatingTableView = false
      dataSourceONE.isUpdatingTableView = false
      self.tableView.dataSource = dataSourceTHREE
      self.activeFRCSource = dataSourceTHREE
    }
    self.tableView.reloadData()
}
```

I think u can add feature it to your DATASource if somebody faced same problem.

**Comment by 3lvis** [comment] 2016-05-22 21:32
Hi @amanbolat, 

Before I had something like what you're showing here, but it ended up introducing more problems than solutions. I'm happy that you got to fix your issue, I still think having multiple-controllers and datasources, or even just updating the predicate when switching datasources could be a better solution.

https://github.com/3lvis/DATASource/blob/master/Source/DATASource.swift#L84-L102

Let me know if I can help with anything else.

Best,

**Comment by 3lvis** [comment] 2016-05-23 22:04
Something like this could help too

http://stackoverflow.com/a/28878191/717416

**Comment by amanbolat** [comment] 2016-05-24 06:14
Thanks, it's good idea. I'll try it too.

**Comment by 3lvis** [comment] 2016-05-24 22:07
@amanbolat Is there a chance you could share a sample project reproducing this issue? Would be nice to get it fixed in case is affecting other users too.

**Comment by amanbolat** [comment] 2016-05-26 07:48
@3lvis  https://github.com/amanbolat/DATASourceMultipleSourceSample
On viewDidLoad it will fetch data and save to core data, then u can delete and fetch again, until u delete go to another segment fetch again and go back to first segment.

**Comment by 3lvis** [comment] 2016-05-26 08:12
@amanbolat thanks a lot! This is very useful.

**Comment by 3lvis** [comment] 2017-07-19 12:22
Doing some spring cleaning, please make a new issue if you still want to do this.

**Closed by 3lvis** 2017-07-19 12:22 UTC
