### ISSUE TITLE
Assertion failure in -[UITableView _endCellAnimationsWithContext

### ISSUE THREAD

**Issue by kermankohli** [3lvis/DATASource#96] opened 2016-12-07 06:56 UTC
Firstly, thank you so much for this library! I've been messing with NSFetchedResultsController + Sections for days now and this just solved all my problems - except one... For some reason I can't get a custom UITableViewCell cell subclass (in Storyboards) to work with this library. 

Any help would be much appreciated.
Thanks in advance!

**Comment by 3lvis** [comment] 2016-12-07 09:08
Hi @kermankohli,

Did you close this because you found a way to do it?

**Comment by kermankohli** [comment] 2016-12-07 09:10
Yeah, it was just the section index title’s that made it look like it was screwing around with the table view. Although, I think I’ve found a bug with the sections...

On Wed, Dec 7, 2016 at 10:08 PM, Elvis Nuñez <notifications@github.com> wrote:
Hi @kermankohli [https://github.com/kermankohli] ,

Did you close this because you found a way to do it?

**Comment by 3lvis** [comment] 2016-12-07 09:11
Let me know if you have something I can reproduce 😁 ❤️

**Comment by kermankohli** [comment] 2016-12-07 09:17
Okay so basically this is the best description I can give of the issue in order to reproduce it"

1. Object A and object B belong in section X.
2. One of object B's property is changed causing it to be removed from section X and form section Y.
3. Object B now changes the property back so it belongs to section X. However, object B doesn't move to section X and instead remains in section Y triggering (Assertion failure in -[UITableView _endCellAnimationsWithContext:)

**Comment by 3lvis** [comment] 2016-12-07 09:22
@kermankohli Thanks Kerman!

I'll try to reproduce it when I get some time.

**Comment by kermankohli** [comment] 2016-12-07 09:24
@3lvis No worries! If you want I can give you the source code of the project since it's not very large and I've been desperately trying to get this to work ahaha.

**Comment by 3lvis** [comment] 2016-12-07 09:25
@kermankohli please do! Try elvisnunez+github@me.com

**Comment by kermankohli** [comment] 2016-12-07 09:30
Do you have a Google-linked email address? I’ll need to add you to the project so you can change the property on the backend

On Wed, Dec 7, 2016 at 10:25 PM, Elvis Nuñez <notifications@github.com> wrote:
@kermankohli [https://github.com/kermankohli] please do! Try elvisnunez+github@me.com [elvisnunez+github@me.com]

**Comment by 3lvis** [comment] 2016-12-07 09:37
@kermankohli let's try in https://gitter.im/SyncDB/DATASource

**Comment by kermankohli** [comment] 2016-12-07 09:40
Sure. I’ve just joined the room.

On Wed, Dec 7, 2016 at 10:37 PM, Elvis Nuñez <notifications@github.com> wrote:
@kermankohli [https://github.com/kermankohli] let's try in https://gitter.im/SyncDB/DATASource [https://gitter.im/SyncDB/DATASource]

**Comment by 3lvis** [comment] 2017-07-19 12:22
Doing some spring cleaning, please make a new issue if you still want to do this.

**Closed by 3lvis** 2017-07-19 12:22 UTC
